version: '3.8'

services:
  app:
    container_name: express-server
    build: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
  db:
    image: postgres:17.6-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: